name: mindwell
description: "MindWell"

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_gemini: ^0.1.2
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  calendar_date_picker2: ^0.5.5


flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/Logo.png'
  image_path_android: 'assets/images/Logo.png'
  image_path_ios: 'assets/images/Logo.png'


dev_dependencies:
  flutter_test:
    sdk: flutter

    

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/

supabase: ^1.5.0
socket_io_client: ^1.0.1

